apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
        - name: go-server
          image: go-server
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: go-server-config

---
apiVersion: v1
kind: Service
metadata:
  name: go-server
spec:
  selector:
    app: go-server
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer
