# # my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "codelab-monitor"

rule_files: []

scrape_configs:
  - job_name: "manka-project"
    static_configs:
      - targets: ["172.23.195.224:4000"]

  - job_name: "node"
    static_configs:
      - targets: ["172.23.195.224:9100"]

  # - job_name: "node-exporter"
  #   static_configs:
  #     - targets: ["node_exporter:9100"]
