global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "codelab-monitor"

rule_files: []

scrape_configs:
  - job_name: "go-server"
    static_configs:
      - targets: ["go-server:4000"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
