// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: chapter/chapter.proto

package chapter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_chapter_chapter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_chapter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_chapter_chapter_proto_rawDescGZIP(), []int{0}
}

func (x *UserRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ChaptersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Chapter       string                 `protobuf:"bytes,2,opt,name=chapter,proto3" json:"chapter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaptersRequest) Reset() {
	*x = ChaptersRequest{}
	mi := &file_chapter_chapter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaptersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaptersRequest) ProtoMessage() {}

func (x *ChaptersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_chapter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaptersRequest.ProtoReflect.Descriptor instead.
func (*ChaptersRequest) Descriptor() ([]byte, []int) {
	return file_chapter_chapter_proto_rawDescGZIP(), []int{1}
}

func (x *ChaptersRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChaptersRequest) GetChapter() string {
	if x != nil {
		return x.Chapter
	}
	return ""
}

type ChaptersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chapter       int32                  `protobuf:"varint,1,opt,name=chapter,proto3" json:"chapter,omitempty"`
	Img           []string               `protobuf:"bytes,2,rep,name=img,proto3" json:"img,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	MangaName     string                 `protobuf:"bytes,4,opt,name=manga_name,json=mangaName,proto3" json:"manga_name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChaptersResponse) Reset() {
	*x = ChaptersResponse{}
	mi := &file_chapter_chapter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaptersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaptersResponse) ProtoMessage() {}

func (x *ChaptersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_chapter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaptersResponse.ProtoReflect.Descriptor instead.
func (*ChaptersResponse) Descriptor() ([]byte, []int) {
	return file_chapter_chapter_proto_rawDescGZIP(), []int{2}
}

func (x *ChaptersResponse) GetChapter() int32 {
	if x != nil {
		return x.Chapter
	}
	return 0
}

func (x *ChaptersResponse) GetImg() []string {
	if x != nil {
		return x.Img
	}
	return nil
}

func (x *ChaptersResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChaptersResponse) GetMangaName() string {
	if x != nil {
		return x.MangaName
	}
	return ""
}

func (x *ChaptersResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_chapter_chapter_proto protoreflect.FileDescriptor

const file_chapter_chapter_proto_rawDesc = "" +
	"\n" +
	"\x15chapter/chapter.proto\x12\achapter\x1a\x1fgoogle/protobuf/timestamp.proto\"&\n" +
	"\vUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"?\n" +
	"\x0fChaptersRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\achapter\x18\x02 \x01(\tR\achapter\"\xac\x01\n" +
	"\x10ChaptersResponse\x12\x18\n" +
	"\achapter\x18\x01 \x01(\x05R\achapter\x12\x10\n" +
	"\x03img\x18\x02 \x03(\tR\x03img\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"manga_name\x18\x04 \x01(\tR\tmangaName\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2T\n" +
	"\x0eChapterService\x12B\n" +
	"\vGetChapters\x12\x18.chapter.ChaptersRequest\x1a\x19.chapter.ChaptersResponseB+Z)github.com/chimas/GoProject/proto/chapterb\x06proto3"

var (
	file_chapter_chapter_proto_rawDescOnce sync.Once
	file_chapter_chapter_proto_rawDescData []byte
)

func file_chapter_chapter_proto_rawDescGZIP() []byte {
	file_chapter_chapter_proto_rawDescOnce.Do(func() {
		file_chapter_chapter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chapter_chapter_proto_rawDesc), len(file_chapter_chapter_proto_rawDesc)))
	})
	return file_chapter_chapter_proto_rawDescData
}

var file_chapter_chapter_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_chapter_chapter_proto_goTypes = []any{
	(*UserRequest)(nil),           // 0: chapter.UserRequest
	(*ChaptersRequest)(nil),       // 1: chapter.ChaptersRequest
	(*ChaptersResponse)(nil),      // 2: chapter.ChaptersResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_chapter_chapter_proto_depIdxs = []int32{
	3, // 0: chapter.ChaptersResponse.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: chapter.ChapterService.GetChapters:input_type -> chapter.ChaptersRequest
	2, // 2: chapter.ChapterService.GetChapters:output_type -> chapter.ChaptersResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chapter_chapter_proto_init() }
func file_chapter_chapter_proto_init() {
	if File_chapter_chapter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chapter_chapter_proto_rawDesc), len(file_chapter_chapter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chapter_chapter_proto_goTypes,
		DependencyIndexes: file_chapter_chapter_proto_depIdxs,
		MessageInfos:      file_chapter_chapter_proto_msgTypes,
	}.Build()
	File_chapter_chapter_proto = out.File
	file_chapter_chapter_proto_goTypes = nil
	file_chapter_chapter_proto_depIdxs = nil
}
