// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: chapter/chapter.proto

package chapter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChapterService_GetChapters_FullMethodName = "/chapter.ChapterService/GetChapters"
)

// ChapterServiceClient is the client API for ChapterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChapterServiceClient interface {
	GetChapters(ctx context.Context, in *ChaptersRequest, opts ...grpc.CallOption) (*ChaptersResponse, error)
}

type chapterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChapterServiceClient(cc grpc.ClientConnInterface) ChapterServiceClient {
	return &chapterServiceClient{cc}
}

func (c *chapterServiceClient) GetChapters(ctx context.Context, in *ChaptersRequest, opts ...grpc.CallOption) (*ChaptersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChaptersResponse)
	err := c.cc.Invoke(ctx, ChapterService_GetChapters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChapterServiceServer is the server API for ChapterService service.
// All implementations must embed UnimplementedChapterServiceServer
// for forward compatibility.
type ChapterServiceServer interface {
	GetChapters(context.Context, *ChaptersRequest) (*ChaptersResponse, error)
	mustEmbedUnimplementedChapterServiceServer()
}

// UnimplementedChapterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChapterServiceServer struct{}

func (UnimplementedChapterServiceServer) GetChapters(context.Context, *ChaptersRequest) (*ChaptersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChapters not implemented")
}
func (UnimplementedChapterServiceServer) mustEmbedUnimplementedChapterServiceServer() {}
func (UnimplementedChapterServiceServer) testEmbeddedByValue()                        {}

// UnsafeChapterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChapterServiceServer will
// result in compilation errors.
type UnsafeChapterServiceServer interface {
	mustEmbedUnimplementedChapterServiceServer()
}

func RegisterChapterServiceServer(s grpc.ServiceRegistrar, srv ChapterServiceServer) {
	// If the following call pancis, it indicates UnimplementedChapterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChapterService_ServiceDesc, srv)
}

func _ChapterService_GetChapters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChaptersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChapterServiceServer).GetChapters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChapterService_GetChapters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChapterServiceServer).GetChapters(ctx, req.(*ChaptersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChapterService_ServiceDesc is the grpc.ServiceDesc for ChapterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChapterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chapter.ChapterService",
	HandlerType: (*ChapterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChapters",
			Handler:    _ChapterService_GetChapters_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chapter/chapter.proto",
}
