// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Anime struct {
	ID            int32         `db:"id" json:"id"`
	Name          string        `db:"name" json:"name"`
	Img           string        `db:"img" json:"img"`
	ImgHeader     string        `db:"imgHeader" json:"imgHeader"`
	Describe      string        `db:"describe" json:"describe"`
	Genres        []string      `db:"genres" json:"genres"`
	Author        pgtype.Text   `db:"author" json:"author"`
	Country       string        `db:"country" json:"country"`
	Published     int32         `db:"published" json:"published"`
	AverageRating pgtype.Float8 `db:"averageRating" json:"averageRating"`
	RatingCount   pgtype.Int4   `db:"ratingCount" json:"ratingCount"`
	Status        string        `db:"status" json:"status"`
	Popularity    pgtype.Int4   `db:"popularity" json:"popularity"`
}

type Chapter struct {
	Chapter   int32            `db:"chapter" json:"chapter"`
	Img       []string         `db:"img" json:"img"`
	Name      string           `db:"name" json:"name"`
	AnimeName string           `db:"animeName" json:"animeName"`
	CreatedAt pgtype.Timestamp `db:"createdAt" json:"createdAt"`
}

type PrismaMigration struct {
	ID                string             `db:"id" json:"id"`
	Checksum          string             `db:"checksum" json:"checksum"`
	FinishedAt        pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	MigrationName     string             `db:"migration_name" json:"migration_name"`
	Logs              pgtype.Text        `db:"logs" json:"logs"`
	RolledBackAt      pgtype.Timestamptz `db:"rolled_back_at" json:"rolled_back_at"`
	StartedAt         pgtype.Timestamptz `db:"started_at" json:"started_at"`
	AppliedStepsCount int32              `db:"applied_steps_count" json:"applied_steps_count"`
}

type User struct {
	ID        string           `db:"id" json:"id"`
	Name      string           `db:"name" json:"name"`
	Email     string           `db:"email" json:"email"`
	Image     string           `db:"image" json:"image"`
	Favorite  []string         `db:"favorite" json:"favorite"`
	CreatedAt pgtype.Timestamp `db:"createdAt" json:"createdAt"`
}
